//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:39:04 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://location.nure.ua/entity", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.nure.location.entity;
